/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        md: {
          bg:       '#07071a',
          surf:     '#0f0f24',
          surf2:    '#161632',
          surf3:    '#1c1c3e',
          surfvar:  '#1e1e40',
          outline:  '#2e2e58',
          outlinevar: '#1e1e3a',
          primary:  '#818cf8',
          primarydim:'#6366f1',
          primarycon:'#1e1b4b',
          onprimary: '#ffffff',
          onprimarycon: '#c7d2fe',
          secondary: '#a78bfa',
          tertiary:  '#34d399',
          error:     '#f87171',
          onsurf:    '#e4e4f8',
          onsurfvar: '#8888c0',
        },
      },
      fontFamily: {
        sans: ['Inter', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'sans-serif'],
        serif: ['Merriweather', 'Georgia', 'serif'],
      },
      borderRadius: {
        'xl2': '20px',
        'xl3': '28px',
      },
      boxShadow: {
        'elev1': '0 1px 3px rgba(0,0,0,0.5), 0 1px 2px rgba(0,0,0,0.4)',
        'elev2': '0 4px 12px rgba(0,0,0,0.5), 0 2px 4px rgba(0,0,0,0.4)',
        'elev3': '0 8px 24px rgba(0,0,0,0.6), 0 4px 8px rgba(0,0,0,0.5)',
        'fabshadow': '0 6px 28px rgba(99,102,241,0.45)',
      },
      keyframes: {
        'viewIn':  { from: { opacity: '0', transform: 'translateY(10px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
        'slideUp': { from: { opacity: '0', transform: 'translateY(24px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
        'fadeIn':  { from: { opacity: '0' }, to: { opacity: '1' } },
        'drawerIn':{ from: { transform: 'translateX(-100%)' }, to: { transform: 'translateX(0)' } },
        'scaleIn': { from: { opacity: '0', transform: 'scale(0.92)' }, to: { opacity: '1', transform: 'scale(1)' } },
        'shimmer': { '0%': { backgroundPosition: '-200% 0' }, '100%': { backgroundPosition: '200% 0' } },
        'ripple':  { to: { transform: 'scale(4)', opacity: '0' } },
        'flipIn':  { from: { transform: 'rotateY(90deg)' }, to: { transform: 'rotateY(0deg)' } },
        'bounce-dot': { '0%,80%,100%': { transform: 'scale(0)' }, '40%': { transform: 'scale(1)' } },
        'progressFill': { from: { width: '0%' } },
        'fabIn':   { from: { opacity: '0', transform: 'scale(0.5) translateY(20px)' }, to: { opacity: '1', transform: 'scale(1) translateY(0)' } },
      },
      animation: {
        'view-in':   'viewIn 240ms cubic-bezier(0.2,0,0,1) both',
        'slide-up':  'slideUp 280ms cubic-bezier(0.2,0,0,1) both',
        'fade-in':   'fadeIn 200ms ease both',
        'drawer-in': 'drawerIn 280ms cubic-bezier(0.2,0,0,1) both',
        'scale-in':  'scaleIn 220ms cubic-bezier(0.2,0,0,1) both',
        'shimmer':   'shimmer 1.5s infinite linear',
        'fab-in':    'fabIn 300ms cubic-bezier(0.34,1.56,0.64,1) both',
        'flip-in':   'flipIn 180ms ease-out both',
        'progress':  'progressFill 900ms cubic-bezier(0.2,0,0,1) both',
      },
    },
  },
  plugins: [],
}
